name: Generer l'APK (rouge)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Scaffold Android si besoin
        run: |
          if [ ! -f "android/gradlew" ]; then
            echo "android incomplet -> on regenere"
            flutter create . --org com.elbouni.annaba --platforms android --project-name el_bouni_pieces_auto
          fi
          ls -la android/

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK debug
        run: flutter build apk --debug --dart-define=APP_VARIANT=v2 --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AJALAK-ROUGE-ELBOUNI-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
